.TH authenticator 1 "authenticator"
.SH NAME
.B authenticator
\- a TOTP authentication application for the GNOME desktop
.SH SYNOPSIS
.B authenticator
.br
.SH DESCRIPTION
.B authenticator
  Authenticator is a GTK3 application for the GNOME desktop, featuring:
  - QR code scanner
  - Beautiful UI
  - Huge database of more than 560 supported services
  - Keep your PIN tokens secure by locking the application with a password
  - Automatically fetch an image for services using their favicon
  - The possibility to add new services
.SH AUTHOR
.B authenticator was written by Bilal Elmoussaoui
